### ISSUE TITLE
`Debug Failure` on Windows

### ISSUE THREAD

**Issue by cawa-93** [johnsoncodehk/vue-tsc#2]
On Windows 10 i got error:
```
C:\Users\kozac\Dev\vite-electron-builder\node_modules\vue-tsc\typescript\lib\typescript.js:2479
            throw e;
            ^

Error: Debug Failure. Expected C:/Users/kozac/Dev/vite-electron-builder/packages/renderer/src/index.ts === C:\Users\kozac\Dev\vite-electron-builder\packages\renderer\src\index.ts.
    at attachFileToDiagnostic (C:\Users\kozac\Dev\vite-electron-builder\node_modules\vue-tsc\typescript\lib\typescript.js:18897:18)
    at Object.attachFileToDiagnostics (C:\Users\kozac\Dev\vite-electron-builder\node_modules\vue-tsc\typescript\lib\typescript.js:18929:42)
    at parseJsonText (C:\Users\kozac\Dev\vite-electron-builder\node_modules\vue-tsc\typescript\lib\typescript.js:29058:46)
    at Object.parseSourceFile (C:\Users\kozac\Dev\vite-electron-builder\node_modules\vue-tsc\typescript\lib\typescript.js:28975:32)
    at Object.createSourceFile (C:\Users\kozac\Dev\vite-electron-builder\node_modules\vue-tsc\typescript\lib\typescript.js:28782:29)
    at transformDiagnostics (C:\Users\kozac\Dev\vite-electron-builder\node_modules\vue-tsc\volar\extension\node_modules\@volar\vscode-vue-languageservice\out\tsProgramApis.js:63:38)
    at Proxy.getSemanticDiagnostics (C:\Users\kozac\Dev\vite-electron-builder\node_modules\vue-tsc\volar\extension\node_modules\@volar\vscode-vue-languageservice\out\tsProgramApis.js:25:16)
    at Object.apply (C:\Users\kozac\Dev\vite-electron-builder\node_modules\vue-tsc\volar\extension\node_modules\@volar\vscode-vue-languageservice\out\languageService.js:341:31)
    at emitFilesAndReportErrors (C:\Users\kozac\Dev\vite-electron-builder\node_modules\vue-tsc\typescript\lib\tsc.js:92270:57)
    at Object.emitFilesAndReportErrorsAndGetExitStatus (C:\Users\kozac\Dev\vite-electron-builder\node_modules\vue-tsc\typescript\lib\tsc.js:92299:18)
```

The problem occurs when finding errors in the `.ts` files. [Like this](https://github.com/cawa-93/vite-electron-builder/blob/9139ea80afe38c922532fb6ce996f8ffce7ea794/packages/renderer/src/index.ts#L10).

At the same time, type checking in GitHub CI (Ubuntu Linux) works [as expected](https://github.com/cawa-93/vite-electron-builder/pull/162/checks?check_run_id=2121208913).

**Comment by johnsoncodehk** [comment]
Fixed in 0.0.13, thanks for the report!
